spring:
  application:
    name: agent-service

  datasource:
    url: jdbc:h2:file:./data/agentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    url: jdbc:h2:mem:agentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
#      ddl-auto: update
#      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  mvc:
    async:
      request-timeout: 60s
    problemdetails:
      enabled: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.example.agent: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: DEBUG
#    org.springframework.transaction: DEBUG


# our properties
app:
  chat:
    max-history-messages: 20
