create TABLE conversations
(
    id         VARCHAR(64) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
);

create TABLE messages
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    conversation_id VARCHAR(64) NOT NULL,
    role            VARCHAR(20) NOT NULL,
    content         VARCHAR(8000) NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_messages_conversation
        FOREIGN KEY (conversation_id)
            REFERENCES conversations (id)
);

create index idx_messages_conversation_id
    on messages (conversation_id);
